services:

  app:
    image: python:3.11-slim  # Use a slim Python image to run Streamlit
    container_name: streamlit_app  # Optional: name your container
    working_dir: /app  # Set the working directory to /app in the container
    volumes:
      - ./app:/app  # Mount the app folder from the host to the container
    ports:
      - "8501:8501"  # Expose Streamlit default port 8501
    command: bash -c "pip install -r /app/requirements.txt && streamlit run /app/src/app.py --server.address 0.0.0.0" # Install requirements and run app
    networks:
      - pokemon_net

networks:
  pokemon_net:
    driver: bridge
